name: Release Please
permissions:
  contents: write
  pull-requests: write
on:
  push:
    branches:
      - master
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: release-please-action
          token: ${{ secrets.GH_TOKEN }}
